### ISSUE TITLE
Use @types/nexus/nexus.d.ts as default typegen output

### ISSUE THREAD

**Issue by Weakky** [prisma-labs/nexus#130]
## Description

In order to make the typegen a bit simpler/transparent for newcomers, I suggest we make `outputs.typegen` optional and use `node_modules/@types/nexus/nexus.d.ts` as a default value when it's not provided

## Note

In order for VSCode to properly catch the types regeneration, you need to first delete the types and then write them again

**Comment by jasonkuhrt** [comment]
> In order to make the typegen a bit simpler/transparent for newcomers

Is there somewhere I can find an explanation of what the feature is for, the expected workflow, and whatever else is pertinent to know about it?

**Comment by jasonkuhrt** [comment]
I attempted this on a project, like so:

```
const schema = makeSchema({
  types: [query, user],
  outputs: {
    schema: path.join(__dirname, "../schema.graphql"),
    typegen: path.join(__dirname, "../node_modules/@types/nexus.d.ts"),
  },
})
```

But it would not get picked up by TypeScript. I tried changing `tsconfig` options, in varying ways and combinations: `compiler.types, compiler.rootTypes, include` but none seemed to have an effect on making TypeScript pickup the file. I tried other locations too. Only the following worked (put nexus.d.ts into project root):

```
const schema = makeSchema({
  types: [query, user],
  outputs: {
    schema: path.join(__dirname, "../schema.graphql"),
    typegen: path.join(__dirname, "../nexus.d.ts"),
  },
})
```

I must be doing something wrong, but unsure.

**Comment by iherger** [comment]
Side note: using `nexus.d.ts` for the typegen output leads to an error when deploying to zeit now, see https://github.com/prisma/nexus-prisma/issues/382

**Comment by jasonkuhrt** [comment]
In response to my own comment, the following would have worked so`@types/<anything>/index.d.ts`.

Closing this in favour of #209.
