### ISSUE TITLE
Move `dynamicOutput/Input` methods into its own makeSchema property

### ISSUE THREAD

**Issue by Weakky** [prisma-labs/nexus#162]
## Description

Currently, all the dynamic method/properties are put in the `makeSchema.types` property, thus mixing actual graphql types and dynamic methods.
I think it can be misleading and they should rather be inputted in another property, such as `plugins`.

## Proposal

```typescript
import { makeSchema, dynamicOutputMethod } from 'nexus'
import * as allTypes from './graphql'

const myPlugin = dynamicOutputMethod({
  name: 'my_plugin',
  factory() {}
})

const schema = makeSchema({
  types: allTypes,
  plugins: [myPlugin]
})
```

While it can appear to be less convenient, I think it could be better for the mental model of what `dynamicMethods` are.

I'm completely opened to different/better naming though, as `plugins` might seem a bit generic 🙌

**Comment by tgriesser** [comment]
Oh yeah I like this idea.

**Comment by jasonkuhrt** [comment]
The ability for users to define these DSL helpers co-located with their GraphQL types and then pass them to nexus without having to tease them apart seems quite useful though, no? Would be curious to explore the tradeoffs here more in depth.

**Comment by tgriesser** [comment]
Closing this as this is now handled via Plugins
