### ISSUE TITLE
[Question]: Any way to get a computed field from children?

### ISSUE THREAD

**Issue by rafamel** [prisma-labs/nexus#175]
Hi there, I'm currently using `nexus` w/ Prisma and I'm finding type inference really great -even if the api is *still* a bit too much on the verbose side for my taste. Overall really great work! I'm fairly new to *graphql* so I'm unsure of what the conventions are, so sorry if this is a bit of an obvious question.

I'd like to define a computed field on a parent using data from a computed field of its children, instead of implementing the same logic again in the parent's resolver.

For the purposes of putting an example forwards, let's say I have a parent `Task` and a set of children `Subtask` living at `Task.subtasks`; while `Subtask.timeLeft` does the computation for the time left for the task, I want to create a `Task.timeLeft` that aggregates all the subtasks time left, how would one go about implementing `Task.timeLeft`?

```javascript
  prismaObjectType({
    name: 'Subtask',
    definition: (t) => {
      t.prismaFields(['*']);
      t.field('timeLeft', {
        type: 'Int',
        nullable: false,
        async resolve(parent, args, { prisma }) {
          // Let's say we're doing some computation here to return the subtask time left
          return 0;
        }
      });
    }
  })
```

**Comment by jasonkuhrt** [comment]
Hey @rafamel, thanks for the succinct question/example. I will treat this as a doc question as I think it would be nice to add the answer to a kind of cook book for others to find. I don't know the immediate answer offhand, will look into it later. One thing I am going to try is: in the parent object, the computed field resolver will receive parent, which should have access to a promise of the sub-task fetches, and in turn then be able to await all to derive its own value.

**Comment by tgriesser** [comment]
Closing this, as this is more of a question for `nexus-prisma`. But just to write how I would go about this/thinking about it in generic GraphQL.

```ts
const Task = objectType({
  name: "Task",
  definition: t => {
    t.int("timeLeft", {
      nullable: false,
      resolve: (task, args, ctx) =>
        ctx.taskData.calculateAllSubtaskTimeLeft(task.id)
    });
    t.list.field("subtasks", {
      resolve: (task, args, ctx) => ctx.taskData.getSubtasks(task.id)
    });
  }
});

const Subtask = objectType({
  name: "Subtask",
  definition: t => {
    t.int("timeLeft", {
      nullable: false,
      resolve: (subtask, args, ctx) =>
        ctx.taskData.calculateSingleSubtaskTimeLeft(subtask.id)
    });
  }
});
```
Essentially, you'd want to decouple the calculation of data from the resolvers, abstracting that into a context object which acts as sort of a container for state local to the GraphQL request.

**Comment by jasonkuhrt** [comment]
Separating the business logic (time left calculation per sub task and aggregate level) from the resolvers is probably going to be the better (than what I'm about to say) thing in most cases, but I think technically a just-dataloader approach _could_ work too.

```ts
const Task = objectType({
  name: 'Task',
  definition: t => {
    t.int('timeLeft', {
      nullable: false,
      resolve: (task, args, ctx) =>
        ctx.taskData
          .getSubtasks(task.id)
          .then(subtasks =>
            subtasks.reduce(
              totalTimeLeft,
              subtask => totalTimeLeft + subtask.timeLeft,
              0,
            ),
          ),
    })
    t.list.field('subtasks', {
      resolve: (task, args, ctx) => ctx.taskData.getSubtasks(task.id),
    })
  },
})

const Subtask = objectType({
  name: 'Subtask',
  definition: t => {
    t.int('timeLeft', {
      nullable: false,
      resolve: (subtask, args, ctx) =>
        ctx.taskData.calculateSingleSubtaskTimeLeft(subtask.id),
    })
  },
})
```
