### ISSUE TITLE
Production mode vs `typegenAutoConfig`

### ISSUE THREAD

**Issue by StevenLangbroek** [prisma-labs/nexus#198]
Hey folks!

We noticed that when running in production mode (NODE_ENV = production) it will correctly opt out of generating artifacts, _but_, nexus will still warn about not being able to generate types. We had to resort to:

```ts
const schemaConfig: SchemaConfig = { /* config */};

if (process.env.NODE_ENV !== 'production') {
  schemaConfig.typegenAutoConfig = {

  }
}
```

I think this should be handled internally by nexus, is that correct? If so I'd gladly contribute a PR to make that work.

**Comment by jasonkuhrt** [comment]
> nexus will still warn about not being able to generate types

What do you mean exactly?

**Comment by jasonkuhrt** [comment]
Hey @StevenLangbroek, yup feel free to contribute said PR. This area will receive attention this quarter.

**Comment by jasonkuhrt** [comment]
Hey @StevenLangbroek what did you mean by:

> nexus will still warn about not being able to generate types

**Comment by ColdStar91** [comment]
I think that’s ideas is so cool
