### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by schickling** [prisma-labs/nexus#2]
A common way to implement authorization rules in JS-based GraphQL servers right now is to use [`graphql-shield`](https://github.com/maticzav/graphql-shield/). While it's possible to use it together with Nexus, I was hoping there was a more "idiomatic" (i.e. type-safe) way to accomplish the same?

**Comment by ChristophDietrich** [comment]
Love to see a direct implementation of rules and authorization in nexus to having cleaner setup and less dependencies.

**Comment by tgriesser** [comment]
Let's move discussion for this over to #23

**Comment by tgriesser** [comment]
Closing this out, as `fieldAuthorizePlugin` now exists in core, and #315 is open for scopes.
