### ISSUE TITLE
default resolver not being called for field unless custom resolver is specificed

### ISSUE THREAD

**Issue by alidcastano** [prisma-labs/nexus#206]
For a new `t.field` with a custom `type` with a `defaultResolver`, the default is not being called unless a custom field `resolver` is specified.

for example, with the following basic model: 

```
export const Child = objectType({
  name: 'Child',
  definition: t => {},
  defaultResolver: (parent) => {
    console.log('called')
    return {}
  }
})
```

with this parent model (without its own `Child.resolve` method), the default resolver is not called:
```
export const ParentModel = objectType({
  name: 'ParentModel',
  definition: t => {
    t.id('id')
    t.field('Child', { type: 'Child' })
  } 
})
```

with this parent model (with its own `Child.resolve` method), the default resolver *is* called:
```
export const ParentModel = objectType({
  name: 'ParentModel',
  definition: t => {
    t.id('id')
    t.field('Child', { 
       type: 'Child',
       resolve: () => { return }
     })
  } 
})
```

But I would have expected the former to work and not the latter. So not sure if this is a bug or If I'm misunderstanding the usage of `defaultResovler`.

**Comment by jasonkuhrt** [comment]
Hey @alidcastano, in the third code snippet did you mean to write:

```ts
...
    t.field('Child', { 
       type: 'Child',
       resolve: () => { return }
     })
...
```

?

**Comment by alidcastano** [comment]
yes, I've edit the snippet to reflect that; thanks

**Comment by tgriesser** [comment]
Hey @alidcastano - thanks for the issue. Unfortunately I'm not sure if this ever worked properly to begin with, I have never used this "feature" myself - and I actually don't think it was a good pattern to support/encourage.

As such, `defaultResolver` has been removed in 0.12.0 in favor of Plugins, which can use the `onCreateFieldResolver` to wrap the `defaultResolver` in a much more configurable way:

https://nexus.js.org/docs/api-plugins
