### ISSUE TITLE
Make schema output with a good defaults

### ISSUE THREAD

**Issue by huv1k** [prisma-labs/nexus#209]
It would be nice to provide good defaults for `outputs` in `makeSchema`. With this `makeSchema` would become a one-liner. Nice default would be one provided in `README`.

Before:
```js
const schema = makeSchema({
  types: [Query],
  outputs: {
    schema: __dirname + "/generated/schema.graphql",
    typegen: __dirname + "/generated/typings.ts",
  },
});
```
After:
```js
const schema = makeSchema({
  types: [Query],
});
```

**Comment by jasonkuhrt** [comment]
Quite similar to #130, just a bit broader in scope and with different suggestion.

**Comment by jasonkuhrt** [comment]
@huv1k will leave this open as is for now, but feel free to close this and contribute your ideas to #130 if you feel that's better.
