### ISSUE TITLE
RelayConnection type naming and extension

### ISSUE THREAD

**Issue by jamiehodge** [prisma-labs/nexus#218]
Two requests regarding the relay connection extension (https://github.com/prisma/nexus/blob/develop/src/extensions/relayConnection.ts):
1. Remove "Relay" prefix from type names and/or make prefix configurable
2. Expose connection definition object (https://github.com/prisma/nexus/blob/develop/src/extensions/relayConnection.ts#L42) to allow arbitrary fields, i.e. `total`.

**Comment by tgriesser** [comment]
Yep, now that plugins are possible this is something we can do, making configurable type-safe abstractions like those needed for connections. Closing in favor of #314, pretty excited about what the API looks like for this so far, should have something in a PR soon.
