### ISSUE TITLE
feature request: create dynamic object types (not just type fields)

### ISSUE THREAD

**Issue by alidcastano** [prisma-labs/nexus#229]
following up on my comment from #98 regarding dynamic object types // cc @jasonkuhrt 

--

currently `dynamicOutputMethod` is more for creating dynamic field types (`t.field`) and there isn't currently a standard/approach for creating dynamic objects. 

example use-case: I need to filter an objects' field relations by the same parent status. specifically, if I query a notebook` Notebook` that has `published: true` then for it's `Notes` I'd like to ensure only published ones are shown as well. 

this could be solved if `apollo-server` gave us access to a grandparent in resolvers but short of that here's code for how I'm currently handling it with nexus: 

```
// create a notebook factory using `DynamicOutputMethod`
dynamicOutputMethod({
  name: 'notebook',
  typeDefinition: `args: {
    typeName: string,
    fieldName: string,
    where: { published: boolean }
  }`,
 factory({ typeDef: t, args }) {
    args.forEach(({ typeName, fieldName, where: { published } }) => {
      const CustomNotebook = objectType({
        name: typeName,
        definition: t => {
          t.string('name')
          t.field('notes', { 
            type: 'Notes', 
            resolve: async (notebook, _, { db }) => db.Note.findMany({ 
              where: { notebookId: notebook.id, published },
            })
          })
        },
      })  

      t.field(fieldName, {
        type: CustomNotebook,
        args: { slugPath: stringArg() },
        resolve: (authUser, { id }, { db }) => db.Notebook.find({
          where: { id, ownerId: authUser.id, published }
        })
      })
    })
})

//  instantiate notebook object type as custom field definition 
objectType({
  type: 'Profile',
  definition: t => {
   t.notebook({
      typeName: 'PublishedNotebook',
      fieldName: 'publishedNotebook',
      where: { published: true }
    })
 }
})
```

other possible solutions I've considered (not currently supported) is nesting field definitions

```
t.field('publishedNotebook', ({
  extend: 'Notebook',
  definition: t => { 
     t.field('notes', {.. })
  }
})
```

**Comment by alidcastano** [comment]
just considered I can use `info.path.prev` to get the grandparent type definition, which might be the easiest approach

**Comment by tgriesser** [comment]
This should be possible in the latest 0.12.0-rc.4, you may want to look at https://github.com/prisma-labs/nexus-prisma to see how they utilize `dynamicOutputProperty`.
