### ISSUE TITLE
Interface as an Input type

### ISSUE THREAD

**Issue by dizzyn** [prisma-labs/nexus#237]
Can you please explain how I can use interface type as an input type argument of MutationField?

Let's take the StarWars example. There is the Character interface implemented for Droid and Human objects. What if i need to create a mutation for saving specified type of Character. What is the type of the argument with data?

````
  t.field('saveCharacter', {
      type: 'Character',
      args: {
        data: arg({
          type: 'Character' <- WHAT TO PUT HERE ?
        })
      },
      ...
    });
````

This demo said: Expected Character to be a possible input type, saw GraphQLInterfaceType

Thank You

**Comment by tgriesser** [comment]
> Let's take the StarWars example. There is the Character interface implemented for Droid and Human objects. What if i need to create a mutation for saving specified type of Character. What is the type of the argument with data?

This is not supported in GraphQL, there is not yet a concept that mirrors `interface` or `union` on the input side, so you would need to create a custom `inputObjectType` here.

```
  t.field('saveCharacter', {
      type: 'Character',
      args: {
        data: arg({
          type: inputObjectType({
             name: 'CharacterInput',
             definition(t) {
               t.string('name')
             }
          })
        })
      },
      ...
    });
```
