### ISSUE TITLE
SHOULD_GENERATE_ARTIFACTS environment variable

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#243]
In discussing with @iherger about https://github.com/prisma-labs/nexus-prisma/issues/430 I realized that users need for a way to explicitly control `config.should_generate_artifacts` from the environment.

1. Typegen is derived data so not committed to the codebase.
2. In the `heroku` system, the build occurs as part of their multi-step deploy pipeline (it runs `npm run build`)
3. In the deploy pipeline `NODE_ENV` is set to `production` (or @iherger did you set that manually? Anyway doesn't really change the point)
4. The app fails to build because TS type checks fail because typegen is not present becuase `NODE_ENV` is `production`.

I propose that we build in support for allowing an environment variable to enable artifact generation. This way Heroku users could for example:

```json5
// package.json
"scripts": {
  "build": "NEXUS_SHOULD_GENERATE_ARTIFACTS=true ts-node src/schema.ts"
```

This would override the check against `NODE_ENV`. It would not override an explicit code setting of `config.should_generate_artifacts === false`.

**Comment by LEOLOVER13** [comment]
use 5.010001;
use strict;
use warnings FATAL => 'all';
use ExtUtils::MakeMaker;

WriteMakefile(
    NAME             => 'Business::OnlinePayment::IPayment',
    AUTHOR           => q{Marco Pessotto <melmothx@gmail.com>},
    VERSION_FROM     => 'lib/Business/OnlinePayment/IPayment.pm',
    ABSTRACT_FROM    => 'lib/Business/OnlinePayment/IPayment.pm',
    LICENSE          => 'Artistic_2_0',
    PL_FILES         => {},
    MIN_PERL_VERSION => 5.010001,
    CONFIGURE_REQUIRES => {
        'ExtUtils::MakeMaker' => 0,
    },
    BUILD_REQUIRES => {
        'Test::More' => 0,
    },
    PREREQ_PM => {
                  'Moo' => 1,
                  'XML::Compile::SOAP' => 0,
                  URI => 1,
                  'Crypt::SSLeay' => 0,
                  'XML::Compile::WSDL11' => 0,
                  'Business::OnlinePayment' => 3,
    },
    dist  => { COMPRESS => 'gzip -9f', SUFFIX => 'gz', },
    clean => { FILES => 'Business-OnlinePayment-IPayment-*' },
);

=over 4

=item trxCurrency

Currency in which the payment is processed. There are all known
three-letter ISO Currency codes allowed. A list of known currency
codes, see L<https://ipayment.de/> under B<Technik>. E.g C<EUR>

CGI Name: C<trx_currency>

Note that the processing of payments in the currency must be agreed
with your payment provider.


Default to C<EUR> in this implementation.

=cut

has trxCurrency => (is => 'ro',
                    default => sub { return 'EUR'},
