### ISSUE TITLE
Improve tooling detection of file changes caused by generation

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#247]
This issue follows up on https://github.com/prisma-labs/nexus/pull/230#discussion_r329192399. If there is a better way for file changes caused by generation to be picked up by VSCode than what we're currently doing, let's definitely do that.

This matters a lot when using @types default typegen paths where failure to detect changes leads to incorrect IDE feedback about state of app (types).

@Weakky can you share more about this?

**Comment by Weakky** [comment]
We found that for VSCode to properly refresh generated typings, it's best to first delete the file and then write it again. Deleting/writing seems to trigger a vscode hook that removes the bug where vscode would not properly refresh the typegen unless you manually walked into that file

**Comment by jasonkuhrt** [comment]
Since we don't have plugins with typegen integration yet we should also port this idea to nexus-prisma.
