### ISSUE TITLE
@types/nexus-typegen package facade

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#253]
Following up on comment in PR https://github.com/prisma-labs/nexus/pull/248#discussion_r332269667.

Labelings this as a bug although its more like covering for a [yarn bug](https://github.com/yarnpkg/yarn/issues/4703).

Maybe we can use this opportunity to produce a package with default typgen which says `ERROR: Please run type generation`

When user does `yarn add|remove ...` all packages get pruned. This cases generated `node_modules/@types/nexus-typegen` to be lost. Reusing the same learnings/motivation already established in https://github.com/prisma/specs/issues/152.

We need to think about what happens if the user customizes their typegen config and so this package would no longer be used as a disk target. We want to make sure what it contains does not conflict with the user's app.

**Comment by jasonkuhrt** [comment]
@divyenduz mentioned verifying facades work smoothly with:

- [ ] Heroku
- [ ] Apex up
- [ ] Netlify

**Comment by jasonkuhrt** [comment]
Related research into this topic at https://github.com/prisma/photonjs/issues/261

Good looking article about working with `@types` here https://skovy.dev/contributing-to-definitely-typed-for-first-time/

**Comment by tgriesser** [comment]
Closing, since we've decided this sort of convention-over-configuration will not be handled at the Nexus layer moving forward.
