### ISSUE TITLE
Is it possible to deprecate a union member?

### ISSUE THREAD

**Issue by vecerek** [prisma-labs/nexus#256]
Hello 👋 
I would like to ask if it's currently possible to deprecate a member of a `union` similarly to deprecating a member of an `enum`? Suppose we have the following union:
```js
const Event = unionType({
  name: "Event",
  definition(t) {
    t.members(
      EventA,
      EventB,
    );
    t.resolveType((item) => item["__typename"]);
  },
});

const EventA = objectType({
  name: "EventA",
  deprecation: "Replaced by EventB", // this doesn't work
  definition(t) {
    t.field("someField", { type: SomeType });
  },
});

const EventB = objectType({
  name: "EventB",
  definition(t) {
    t.boolean("someOtherField");
  },
});
```

With `enum`s we could just do the following but not with unions as far as I know:
```js
const MyEnum = enumType({
  name: "MyEnum",
  members: [
    { name: "EnumA", deprecation: "Replaced by EnumB" },
    "EnumB",
  ],
});
```

**Comment by tgriesser** [comment]
It is not, but only because this is not supported by GraphQL / `graphql-js`. If this changes in the spec we will add this behavior to nexus, but at present it is out of scope for the library.

Related: https://github.com/graphql/graphql-spec/issues/197#issue-166400619

**Comment by tiago-loureiro** [comment]
Hi @tgriesser - going through the issues, it seems like it is now https://github.com/graphql/graphql-spec/pull/525 - would it make sense to revisit it?
