### ISSUE TITLE
facebook messenger qr code scanner reader ( Custom Pattern ) like snapchat / Wechat

### ISSUE THREAD

**Issue by FeddiGhani** [prisma-labs/nexus#260]

**Comment by Weakky** [comment]
Closing your issue as no description is provided and what you're asking for is unclear. Please create another one if needed

**Comment by jasonkuhrt** [comment]
I think its a spam of some sort, see another bizarre action by this user/bot here: https://github.com/prisma-labs/nexus/pull/259.
