### ISSUE TITLE
Nexus CLI

### ISSUE THREAD

**Issue by schickling** [prisma-labs/nexus#264]
To improve Nexus related development workflows, I think there's room for a Nexus CLI which could be used for the following:

- `npx nexus init` / `npm init nexus`: Set up a new Nexus project
- `nexus dev`: Start a development server
- Plugin integrations (e.g. run `prisma dev` via `nexus dev`)

**Comment by jasonkuhrt** [comment]
Related to #275 

But as @tgriesser pointed out (and I agree) we don't want a CLI in the this core lib.

Once we have a higher order tool, we can revisit the concept of a CLI.
