### ISSUE TITLE
__dirname in schema + typegen paths not settable in lambda environments

### ISSUE THREAD

**Issue by seanemmer** [prisma-labs/nexus#270]
I have set up Nexus in a Zeit Now environment which I am running locally using `now dev`.

This creates a local lambda running in the /private/var folder.  Unfortunately, `__dirname` points to this folder and not my local project folder when it is executed inside of the lambda.  

This makes the generated typegen and schema inaccessible to my local project folder.  The only workaround I have found to run a separate ts-node process to generate a new typegen + schema every time I update my code.

I believe this may be the cause of https://github.com/prisma-labs/nexus-prisma/issues/382 as well.

**Comment by jasonkuhrt** [comment]
@seanemmer I'm not familiar with zeit, if you can share a minimal repro I could try it out and maybe document a good pattern to work with it. Have you tried with the new `@types` defaults? https://github.com/prisma-labs/nexus/blob/develop/CHANGELOG.md#beta12 You shouldn't be needing to configure outputs anymore.

**Comment by seanemmer** [comment]
[repro.zip](https://github.com/prisma-labs/nexus/files/3731787/repro.zip)
@jasonkuhrt thanks for helping out.  The new @types defaults do not work, I'm assuming they still use __dirname under the hood.

In order to reproduce:

`cd repro && npm install -g now && now dev`
Visit localhost:3000/api and you will see that __dirname refers to a lambda directory.  Basically we need a way to set the output paths at buildtime rather than runtime.

**Comment by jasonkuhrt** [comment]
Hey @seanemmer looking into this more now. Thanks for the info to date.

**Comment by jasonkuhrt** [comment]
@seanemmer documented a workflow for zeit that seems reasonable. If you find ways to improve it PRs are welcome :).

**Comment by seanemmer** [comment]
Thanks @jasonkuhrt !
