### ISSUE TITLE
Prisma2 page not found 404

### ISSUE THREAD

**Issue by deadcoder0904** [prisma-labs/nexus#273]
This is weird 🤷‍♂️

![prisma2 404](https://user-images.githubusercontent.com/16436270/67002169-f2593900-f0f8-11e9-809e-c91dd1e69e23.png)

**Comment by deadcoder0904** [comment]
It doesn't work with Prisma 1 either → https://nexus.js.org/docs/database-access-with-prisma

**Comment by deadcoder0904** [comment]
I should have opened it here https://github.com/prisma-labs/nexus-prisma, mind to transfer?

**Comment by jasonkuhrt** [comment]
@deadcoder0904 Site publishing is out of my hands currently. Closing this because those pages will no longer exist anyways. The next publish changes things a bit and nexus-prisma reference is for now here https://github.com/prisma-labs/nexus-prisma.

**Comment by deadcoder0904** [comment]
Well, @jasonkuhrt can u remove the link from that repo as well then. It obviously links to 404. It's confusing 😕

<img width="1440" alt="404" src="https://user-images.githubusercontent.com/16436270/67094164-d45f0780-f1d0-11e9-9b98-4884eaa94e4d.png">

**Comment by jasonkuhrt** [comment]
@deadcoder0904 Absolutely! Thanks for pointing that out 🙏
