### ISSUE TITLE
Error generating outputs

### ISSUE THREAD

**Issue by jaimealv994** [prisma-labs/nexus#278]
Hello, I am trying nexus but I am getting the following error, the server runs and I can query data but the outputs are not being generated

```
Serverless: POST /hello (λ: hello)
[Error: UNKNOWN: unknown error, mkdir] {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'mkdir'
}
```

The stack I am using is apollo-server-lambda with Typescript and this is my handler

```
import {ApolloServer} from 'apollo-server-lambda'
import {makeSchema, queryType, stringArg} from 'nexus';
import * as types from './types'

const Query = queryType({
    definition(t) {
        t.string("hello", {
            args: {name: stringArg({nullable: true})},
            resolve: (parent, {name}) => `Hello ${name || "World"}!`,
        });
    },
});

const schema = makeSchema({
    types: types,
    outputs: {
        schema: __dirname + "/generated/schema.graphql",
        typegen: __dirname + "/generated/typings.ts",
    },
});


const server = new ApolloServer({
    schema,
    playground: true,
    introspection: true,
});

export const hello = server.createHandler();
```

I don't know if it is something related to serverless or the OS  I am using. I am also getting some warnings like

- Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

- WARNING in ./node_modules/prettier/parser-glimmer.js 1:127549-127567
require.extensions is not supported by webpack. Use a loader instead.

**Comment by jasonkuhrt** [comment]
Hey @jaimealv994 can you share a repro repo we can checkout? You should not have to configure `outputs` at all. Please use the defaults if possible and if they're not working we'd love to know more about it.

**Comment by jaimealv994** [comment]
Hi @jasonkuhrt I made it work by changing

``` javascript
const schema = makeSchema({
    types,
    outputs: {
        schema: __dirname + "/generated/schema.graphql",
        typegen: __dirname + "/generated/typings.ts",
    },
});
```
for
``` javascript
const schema = makeSchema({
    types,,
    outputs: {
        schema: path.resolve('./src/generated/schema.graphql'),
        typegen: path.resolve('./src/generated/nexus.ts'),
    },
});
```

**Comment by jasonkuhrt** [comment]
Thanks @jaimealv994, what happens when you set `outputs` to `true`? Why doesn't that work for you?

**Comment by jaimealv994** [comment]
if I use `outputs: true`, the project starts, I can execute queries but I lose TypeScript, IntelliSense and autocomplete are broken, so I don't have any suggestion about what to return in my resolvers. **Types and schema are not being generated**.

If I use `outputs: {schema: __dirname + "/generated/schema.graphql",  typegen: __dirname + "/generated/typings.ts"}` I get the following error:

```
Error: Expected path for outputs.typegen to be a string, saw src/generated/typings.ts
    at Object../node_modules/nexus/dist/utils.js.exports.assertAbsolutePath (C:\Users\jalvarez\Desktop\projects\mi_ganado_api\.webpack\service\src\webpack:\node_modules\nexus\dist\utils.js:111:1)

```

`__dirname + "/generated/schema.graphql"` is giving me a relative path which seems to be causing the problem, `schema: path.resolve('./src/generated/schema.graphql'),` gives me an absolute path which is working.

**Comment by jasonkuhrt** [comment]
> but I lose TypeScript, IntelliSense and autocomplete are broken, so I don't have any suggestion about what to return in my resolvers. Types and schema are not being generated.

Hm, that is not what should be happened.

Can you share your `tsconfig.json` with us?

Also can you confirm that `node_modules/@types/nexus-typegen/index.ts` is being generated or not?

**Comment by jaimealv994** [comment]
This is my tsconfig.json

```
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es6",
    "lib": [
      "esnext"
    ],
    "moduleResolution": "node",
    "strictNullChecks": true,
    "rootDir": "./src",
    "pretty": true
  },
  "include": [
    "src/**/*",
    "typings/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}

```


I checked `node_modules/@types/nexus-typegen/index.ts` and it is not being generated

**Comment by jasonkuhrt** [comment]
> I checked node_modules/@types/nexus-typegen/index.ts and it is not being generated

Even when you set `outputs: true`?

**Comment by jaimealv994** [comment]
Yes, even when I set `outputs: true`  `node_modules/@types/nexus-typegen/index.ts` is not being generated.

![image](https://user-images.githubusercontent.com/36939361/67953738-51b54f80-fbb5-11e9-90c1-ded1e8d9beae.png)

**Comment by jasonkuhrt** [comment]
What version of `nexus` are you using? Is `shouldGenerateArtifacts` true (or env var `NEXUS_SHOULD_GENERATE_ARTIFACTS`)? Sometimes vscode tree lags behind, ensure to refresh or just use `ls` in terminal.

**Comment by tgriesser** [comment]
I believe the warning for this is clearer in 0.12.0. 

The docs have also been updated to explain the arguments to `makeSchema` a bit better. https://nexus.js.org/docs/api-makeSchema - `outputs: true` is no longer supported in `nexus` directly, because of the different sources of potential confusion, it has been moved to https://github.com/prisma-labs/nexus-prisma/pull/521

Closing as I don't believe there is anything actionable here without more information.
