### ISSUE TITLE
Expose lifecycle phase to plugins

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#289]
We are finding ourselves blocked from reaching an ideal solution on https://github.com/prisma-labs/nexus-prisma/issues/472 because there is no way for the plugin to tell which phase of execution it is in.

The idea here is that plugins could do something like:

```ts
if (builder.phase !== 'walk') {
    console.warn('something')
}
```

**Comment by jasonkuhrt** [comment]
CC @tgriesser

**Comment by tgriesser** [comment]
I don't believe you even need this on plugins, just on dynamics. What do you think about  #293
