### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by chrisdrackett** [prisma-labs/nexus#296]
I'm trying to wrap my head around the best way to handle errors. At the moment given the following code:

```js
    t.field('testError', {
      type: 'String',
      resolve: async () => {
        throw new Error('Custom Error')
        return 'No Error'
      },
    })
```

I would expect to see `Custom Error` come through on the client. Instead I see:

```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Mutation.testError.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testError"
      ]
    }
  ]
}
```

Is there a way I can send my own error to the client instead of the error for nexus?

**Comment by jferrettiboke** [comment]
That should work.

I think the error is coming from other fields of the mutation. Try to query only the `testError` field and forget about other fields in your mutation.

**Comment by chrisdrackett** [comment]
this ended up being an issue with some middleware we had forgotten we had installed. Sorry for the invalid issue!
