### ISSUE TITLE
Override `printSchema`

### ISSUE THREAD

**Issue by Weakky** [prisma-labs/nexus#3]
## Description

We'd like to be able to re-order how the schema is printed, mostly to put the `Query` and `Mutation` type on top of the file vs. the alphabetical order that is made at the moment.

As we're importing types from `prisma` with `nexus-prisma`, it creates a lot of noise especially with input types being huge. For that reason, it'd be useful for us to be able to decide how the schema is printed

**Comment by tgriesser** [comment]
I'm actually thinking of adding more config options for `makeSchema` to tap into important pieces of the schema construction or execution processes, e.g. the `missingType` that nexus-prisma uses to catch missing types. Or for the authorization pieces, a way to handle/format the error. Or for non-null errors ways to gracefully recover from it without crashing the entire Query.

Basically a more well defined middleware system.

Perhaps `printSchema` could be one of these configs?

```ts
makeSchema({
   types: [ /* ... */ ],
   outputs: { /* ... */ },
   printSchema(schema) {
      return myCustomPrintSchema(schema)
   }
})
```

**Comment by Weakky** [comment]
Hey Tim,

Sounds great! That would indeed work perfectly for me. That would let me override `printSchema` from `makePrismaSchema` if none is provided 🙌

**Comment by tgriesser** [comment]
@Weakky is this still something you're looking for?
