### ISSUE TITLE
Type resolvers as functions

### ISSUE THREAD

**Issue by dizzyn** [prisma-labs/nexus#302]
Hi, please. Is there a way to call type resolvers directly (as functions)? I would like to use them for the optimistic UI to get counted fields values.

````
export const Image = objectType({
  name: 'Image',
  definition(t) {
    t.string('type');
    t.field('typeName', {
      type: 'String',
      resolve: ({ type }) => EnumNames[type]
    });
  }
});

const newImageResolved = Image({type: "Full"}) <== what to do here?
````

Thank You

**Comment by tgriesser** [comment]
I don't see this as something that could/should be possible to do with Nexus. I do want to think about the general idea a bit more though, because I have wondered if there's a simpler way to construct Nexus types from value objects.

What is your use case? Are you currently attempting to use the code associated with Nexus definitions on the frontend?

**Comment by dizzyn** [comment]
The use case is this:
- I have Apollo client and perform optimistic updates
- On the server side there is simple Prisma schema
- After creating new record (Image) I can construct all the fields on the client side for that Optimistic update. But I'm missing the counted fields (typeName) that are in the objectType definitions.


There is my workaround with code duplicities:
````
const [createImage] = useMutation<TCreateImage, { image: TImage }>(
    CREATE_IMAGE,
    {
      optimisticResponse: ({ image }) => {
        return ({
          createImage: {
           image: {
             ...image,
            typeName: EnumNames[image.type]}  <== this is the code duplicity
          }
        })
      },
    }
  );
````

Desired solution would be:
````
         return ({
          createImage: {
           image: Image(image) 
          }
        })
````

I have tried to build the whole schema `makeSchema` but there is dependency 'fs' so it can not be used in the browser.

Maybe this scenario is far away from your plan wit the library. Please consider my approach. I can also prepare a sandbox with working demo if you want.

Thank you and have a nice day.

**Comment by dizzyn** [comment]
Hi, I have discussed this widely and have one additional view. Sometimes the whole graphql structure runs on client side without server (eg. https://github.com/hasura/client-side-graphql). That is quite common scenario. My case is pretty similar.

Seems that the only obstacle for me is that the Nexus schema is not possible to be builded in the browser if i understand that right. 

So that I would like to ask you how match the "makeSchema" depends on Node API.

Thank you for the answer and the great package.

**Comment by tgriesser** [comment]
> typeName: EnumNames[image.type]}  <== this is the code duplicity

Any time you have an isomorphic app, you're going to have a little duplicity. I think it may be best to just have a common package that constants are shared from, so `EnumNames` can be imported in both contexts without the baggage of everything else that should only exist server-side.

> I have tried to build the whole schema makeSchema but there is dependency 'fs' so it can not be used in the browser.

I don't think there's enough value here to try to get this running on the client side - it's not the intended target. If this is truly desired, it should be possible to customize a webpack build in such a way that these are shimmed. PR's are welcome if there's anything that would help with that.

Closing as I don't see this as anything we will plan on supporting.
