### ISSUE TITLE
Remove NEXUS_SHOULD_GENERATE_ARTIFACTS

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#303]
We will revert #243 because we have decided to officially make `nexus` a lower level tool optimized for higher order tooling first and foremost.

We should do this in two steps:

1. Deprecate #243 in 0.12.x
2. Outright remove it in 0.13.x

Users can use a higher order tool (at Prisma we're kicking off work on a prototype soon), build/use plugins, or just inline logic like as follows:

```ts
makeSchema({
  shouldGenerateArtifacts: process.env.NEXUS_SHOULD_GENERATE_ARTIFACTS === 'true' || process.env.NODE_ENV !== 'production',
  // ...
})
```

**Comment by tgriesser** [comment]
I do not plan on removing this in two steps, it was only ever available via a beta release (only relatively recently), and it has already been removed in #242 and is documented in the changelog on that branch as such. 

There are now console warnings if the `outputs` is missing and better documentation. Going to close this, as the work for removing this has already been done, as well as porting the relevant logic to https://github.com/prisma-labs/nexus-prisma/pull/521 if you plan for more of a graceful degradation strategy there.
