### ISSUE TITLE
Remove user-friendly outputs defaults

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/nexus#304]
We will revert Revert https://github.com/prisma-labs/nexus/issues/209 / https://github.com/prisma-labs/nexus/pull/230 / #130 because we have decided to officially make nexus a lower level tool optimized for higher order tooling first and foremost.

Users can use a higher order tool (at Prisma we're kicking off work on a prototype soon) or build/use plugins.

**Comment by tgriesser** [comment]
These are all reverted already in #242, which I was planning on merging as soon as you are ready to go with https://github.com/prisma-labs/nexus-prisma/pull/521

**Comment by jasonkuhrt** [comment]
> as soon as you are ready to go with prisma-labs/nexus-prisma#521

@Weakky and/or I will get back to you tomorrow it 👍

**Comment by tgriesser** [comment]
Cool, looks like https://github.com/prisma-labs/nexus-prisma/pull/521 was merged, nice!
