### ISSUE TITLE
InputObjectType not generated in schema when using arg()

### ISSUE THREAD

**Issue by vjsingh** [prisma-labs/nexus#321]
Below, example (1) generates CustomType in my ```generated/schema.graphql```, whereas example (2) does not. This is a problem because my tooling needs to know the types for the client-side.

```
const CustomType = inputObjectType({
  name: 'CustomType',
  definition(t) {
    t.string('name', { required: true });
  },
});
```

**1.** 
```
t.field('aField', {
  ...
  args: {
    data: CustomType,
  },
```

**2.** 
```
t.field('aField', {
  ...
  args: {
     data: arg({
        type: 'CustomType',
        required: true,
        list: true,
        }),
  },
```

**Comment by vjsingh** [comment]
@tgriesser Thanks very much for the quick response, that did the trick.

Just some feedback / food for thought: It took me a while to debug, since all of my other `InputObjectType`s so far have been of form (1) instead of (2), so I couldn't figure out what was going wrong. I also don't see much documentation about `InputObjectType`s in the Nexus docs, the nexus-prisma docs, or the examples, so I had trouble learning about and isolating the issue. I'm not sure if there's an example that includes a list of a custom `InputObjectType` as I'm using?

That said thanks for your work on this excellent library.

**Comment by tgriesser** [comment]
`InputObjectType` is really no different than any other type in how it is defined, and used: 
https://nexus.js.org/docs/api-inputobjecttype

Feel free to open a PR with any improvements you think can be made to the docs.
