### ISSUE TITLE
Union & type issues after updating from beta-6 to rc-5

### ISSUE THREAD

**Issue by StevenLangbroek** [prisma-labs/nexus#329]
Hey folks!

I'm trying to update from beta-6 to rc-5, and I'm now getting this type error on our unions:

![image](https://user-images.githubusercontent.com/296796/69378104-f2c39180-0cad-11ea-9eaa-f62024f4af04.png)

Interestingly, if I change it to `AuthenticationError.name`, the type error moves on to the next member and so on until I've done them all...

I don't fully understand what's happening here, any thoughts?

**Comment by StevenLangbroek** [comment]
(these members are `objectType`s btw)

**Comment by Ericnr** [comment]
I get the exact same bug. It compiles just fine but VScode complains

**Comment by Ericnr** [comment]
can we have feedback on this? It prevents me from compiling my project.

**Comment by tgriesser** [comment]
Will take a look.

**Comment by tgriesser** [comment]
This should be fixed in `0.12.0-rc.6`, let me know if you're still having any issues.

**Comment by Ericnr** [comment]
working good!
