### ISSUE TITLE
Type `resolve` args

### ISSUE THREAD

**Issue by lcswillems** [prisma-labs/nexus#332]
It would be nice if `resolve` args could be typed as I already provide the type of the args.

My code:

```js
export const AuthQueryType = queryType({
  definition(t) {
    t.string('signin', {
      args: { email: stringArg(), password: stringArg() },
      resolve: async (_root, { email, password }) => {
        //
      }
    });
  }
});
```

`email` and `password` have type `any`.

**Comment by tgriesser** [comment]
They should be, at least after the code is executed for the first run, do you have your `makeSchema` setup to output the type definitions?

**Comment by lcswillems** [comment]
They are indeed. I didn't get the typing because I got a TypeScript error somewhere in my code and the server had not restarted.
