### ISSUE TITLE
Re-thinking the usage of a package facade

### ISSUE THREAD

**Issue by kripod** [prisma-labs/nexus#340]
As outlined in #253, a package facade could be used as the `makeSchema` function's `outputs.typegen` parameter by default, unless overrided explicitly. By using a facade, [multiple workarounds](https://github.com/kripod/exigo/blob/f834a432d104783042e82f7523644d78a55941e8/server/src/functions/graphql/schema/index.ts#L26-L36) could be resolved at package level, available out of the box for everyone.

Experimentation with the `@prisma/photon` package could be taken as an example for implementing a similar approach with nexus and [nexus-prisma](https://github.com/prisma-labs/nexus-prisma).

As an additional benefit, this change may eliminate the need for a `prettierConfig` option, as files in `node_modules` don't have to match the style of source code checked into SCM.

**Comment by jasonkuhrt** [comment]
@kripod we've gone through this over the past few months. We got half way there then removed the feature. Therefore I can safely say this feature will not be getting addressed at the nexus library level.

It will be up to higher order tooling to address this issue. The good news is we're already on it. Stay tuned.
