### ISSUE TITLE
Property does not exist on type 'ObjectDefinitionBlock<"Query">'

### ISSUE THREAD

**Issue by lcswillems** [prisma-labs/nexus#342]
I can't use `t.void` (where `void` is a custom scalar) in an object type definition.

This is my code:

```
import { queryType, makeSchema, scalarType } from "nexus";
import { GraphQLServer } from "graphql-yoga";

const VoidScalar = scalarType({
  name: "Void",
  asNexusMethod: "void",
  parseValue() {},
  serialize() {},
  parseLiteral() {}
});
const Query = queryType({
  definition(t) {
    t.void("myField", {
      nullable: true,
      resolve: () => {}
    });
  }
});

const schema = makeSchema({
  types: [VoidScalar, Query],
  outputs: {
    schema: __dirname + "/generated/schema.graphql",
    typegen: __dirname + "/generated/typings.ts"
  }
});

new GraphQLServer({ schema });
```

It shows this error:

```
index.ts:13:7 - error TS2339: Property 'void' does not exist on type 'ObjectDefinitionBlock<"Query">'.
```

# To reproduce

1. `git clone https://github.com/lcswillems/nexus-bug`
2. `yarn install`
3. `yarn ts-node-dev index.ts`

**Comment by Nayni** [comment]
You're running into the chicken or the egg problem here. Nexus works in a way that it generates type definitions based on the schema that you write. However in order for your application to fully work those type definitions need to be generated first. In order to generate them you have to start up the server.

A sort of best practice when developing with nexus is to startup your server using the `--transpileOnly` flag so that even though there are missing type definitions the server can still start.

I think this is an important detail which isn't highlighted enough in the docs. If you have a look at all the examples in the repo you'll notice that all of them have a `start` script that looks like this: `"start": "ts-node-dev --no-notify --transpileOnly --respawn ./src"`. 

Another option is to have a separate script to run without starting up your server and calling `makeSchema` just to generate type definitions.

**Comment by lcswillems** [comment]
Thanks a lot for your answer!!

But, I am not sure to understand why `--transpileOnly` solves the issue. With `--transpileOnly`, there is no type checking? So why using TypeScript in this case?

**Comment by Nayni** [comment]
You won't have type checking when running the server in development mode. You're IDE or a regular typescript compile will still catch all the errors.

You're indeed giving up a little bit of the TypeScript type safety but there should be enough other tooling that can catch any errors you do make:
- Your IDE should be giving you warnings/errors
- Your CI (or even a simple commit hook) should still perform a full compile and type check, catching any forgotten errors

If you prefer to always catch errors early another approach is to set up a workflow as follows:
- Create a `createSchema.ts` file containing the `makeSchema` call to perform the type generation by Nexus
- Create a npm script calling this function, it shouldn't run the server, just `makeSchema` and exit
- Use a tools like `nodemon` and `concurrently` to run the `createSchema` script and booting up your server in sequence.
- Now everytime you make a change in your code, it should perform a `makeSchema` call first making your type definitions complete and then reboot the server (without the `--transpileOnly`) flag. If you still have type errors after the new type definitions are generated, your server won't start until you fix the issues.

This is also a valid workflow but requires a little more setup to get right. I personally prefer the `--transpileOnly` workflow and let other tooling like my IDE and CI pick up anything I didn't see.

**Comment by lcswillems** [comment]
Thank you so much for your answer!! I have a very good understanding of all the solutions available now. Thanks a lot!

**Comment by Ericnr** [comment]
I'm getting the problem even if I run --transpileOnly first. The types for the scalar are generated but TS still complains whenever I try to compile. @lcswillems did you get it working?

**Comment by lcswillems** [comment]
No, I didn't. As Beta 14 works for me, I changed nothing

**Comment by Ericnr** [comment]
uh, I still get the same errors in beta14

**Comment by lcswillems** [comment]
Sorry! I thought you were posting your message on this issue where I also participate: https://github.com/prisma-labs/nexus/issues/327 . I mixed the issues.

So, no, I have not tried. Currently, I use it like this:

```
t.field('myfield', {type: 'MyType'})
```

instead of

```
t.myType('myfield')
```

This doesn't give me errors.

**Comment by Ericnr** [comment]
Cool, that works for me too. Opened a new issue to follow this up.
