### ISSUE TITLE
is there any way to generate document? 

### ISSUE THREAD

**Issue by saostad** [prisma-labs/nexus#353]
I always use schema and generate types from that file but for client-side type generation in graphql-code-generator it needs document file. https://graphql-code-generator.com/docs/getting-started/documents-field

what I technically need are all possible queries, mutations, and subscriptions for client-side use.

**Comment by Ericnr** [comment]
I think that might not be the purpose of this lib. The code generator works very well for me.

**Comment by jasonkuhrt** [comment]
IIUC gql code generator refers to graphql SDL files as “documents”. Nexus can generate one if you want. Look under outputs config of nexus.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saostad** [comment]
could you please show me the link to that part of the documentation? 
there is nothing related to output in [Type Generation](https://nexus.js.org/docs/type-generation) or [makeSchema](https://nexus.js.org/docs/api-makeschema)

**Comment by tgriesser** [comment]
Sorry, I think @jasonkuhrt is mistaken, the "documents" graphql code generator is looking for are the client side queries & mutations for your client-side, contained either in `.graphql` files or in tagged template literals - Nexus has no opinions on how and where these are created, it's up to your client-side application.

**Comment by saostad** [comment]
I found a library that do the job [gql-generator](https://www.npmjs.com/package/gql-generator)

**Comment by jasonkuhrt** [comment]
@tgriesser Thanks for the correction
