### ISSUE TITLE
Defining list of lists

### ISSUE THREAD

**Issue by thehappycoder** [prisma-labs/nexus#354]
Is it possible to define a field of output type `list of lists of custom type`?

**Comment by tgriesser** [comment]
This is possible via `list: array`:
```ts
t.float('coords', {
  list: [true, true]
})
// coords: [[Float!]!]
```

Where the boolean exists to indicate whether the type is non-nullable or not. This API is a little confusing, I may look to allow for something closer to graphql-js with wrapping types in the future.

**Comment by HosseinAgha** [comment]
@tgriesser, This is indeed very confusing. We are using nexus for quite some time now and I just understood why the `list` property is an array of booleans!
