### ISSUE TITLE
In a mutation, how do I accept an array of objects?

### ISSUE THREAD

**Issue by JasonZStanley** [prisma-labs/nexus#356]
I am trying to create a mutation which accepts the following data structure:

```
{
  name: "Some name",
  tasks: [
    {
      name: "Some Task", // string
      frequency: 1 // int
    }
  ]
}
```

In my code I have a starting point like this. This is creating the mutation type.

```
t.field('createGoal', {
        type: 'Goal',
        args: {
            name: stringArg(),
            // I am not sure how to define an array of objects here.
        },
        // ... stuff
});
```

I had a browse of the docs but couldn't find the syntax to do this. Could someone link me to where this is specified in the docs or an example of how to achieve this. Thanks

**Comment by DaVinciLord** [comment]
It's pretty simple, you can do that:

```
const TaskInput = inputObjectType({
  name: 'TaskInput', 
  definition: (t) {
    t.string('name', options)
    t.int('frequency', options2) 
 }
}) 

t.field('createGoal', {
        type: 'Goal',
        args: {
            name: stringArg(),
            tasks: arg({ type: TaskInput, list: true, nullable: false }) 
        },
        // ... stuff
});
```

That should do the trick, you'll have an argument which takes a list of `TaskInput`.

**Comment by JasonZStanley** [comment]
Thanks a lot for your help. I figured it would be straightforward.
