### ISSUE TITLE
Subscription with subscriptionField  return `"data": null`

### ISSUE THREAD

**Issue by batFormat** [prisma-labs/nexus#366]
Subscription return `"data": null`

```
 pubsub.publish("transaction", { transaction })
```

```
import { subscriptionField } from 'nexus'

export const Subscription = subscriptionField('transaction', {
  type: 'Transaction',
  subscribe: (root, args, ctx) => ctx.pubsub.asyncIterator(['transaction']),
  resolve: payload => {
    return payload
  },
})
```

**Comment by AndresRodH** [comment]
I believe the issue relies on this line `pubsub.publish("transaction", { transaction })`

You are publishing an object with a transaction property which is a transaction type. You can do two things:

You could make a subscription payload. This matches the payload you are sending and is more flexible if you wanted to send more data with the subscription
```
const TransactionSubscriptionPayload = objectType({
  name: 'TransactionSubscriptionPayload',
  definition(t) {
    t.field('transaction', { type: 'Transaction })
  }
})
```

Or you can simply just send the transaction object `pubsub.publish("transaction", transaction)`

**Comment by batFormat** [comment]
@AndresRodH Big thanks! You save my day!
