### ISSUE TITLE
Request an example with pagination dynamic data

### ISSUE THREAD

**Issue by nghiepit** [prisma-labs/nexus#370]
Hi guys,
I have read through this section [Connection Plugin](https://nexus.js.org/docs/plugin-connection).
May not fully understand paging in GraphQL.
All examples are paging with fixed small data.
I could not query all the data up to millions of records then processing pagination.

#### With `resolve`
```js
export const usersQueryField = queryField((t) => {
  t.connectionField("users", {
    type: User,
    async resolve(root, args, ctx, info) {
      // HERE ↓
      return connectionFromArray(await ctx.resolveUserNodes(), args);
    },
  });
});
```

#### With `nodes`
```js
t.connectionField("users", {
  type: User,
  nodes(root, args, ctx, info) {
    // HERE → [{ id: 1,  ... }, ..., { id: 10, ... }]
    return ctx.users.resolveForConnection(root, args, ctx, info);
  },
});
```

Thank you in advance.

**Comment by seanemmer** [comment]
Would also love some guidance on this - when I attempt to use an async function for the nodes argument (i.e. to connect to Prisma Client) I get a type error from the nodes property.  A practical example would be helpful.

**Comment by santialbo** [comment]
If you are fetching the slice of data from a database you need to use `connectionFromArraySlice`. It's not very well documented on the relay docs but if you have a look at the implementation you should be able to figure out how to use it.
https://github.com/graphql/graphql-relay-js/blob/677e6cc50b1bd53433ef10b289417eaf1056013c/src/connection/arrayconnection.js#L58

The main idea is that you pass it a slice big enough (can be the same size as the slice requested) to cover the slice of data requested.
