### ISSUE TITLE
Cannot find module 'graphql-query-complexity'

### ISSUE THREAD

**Issue by ChristianBoehlke** [prisma-labs/nexus#376]
Hello,

With the latest `0.12.0-rc.10`, we are getting the following error during our TypeScript check even though we are not using this plugin.

`node_modules/nexus/dist/plugins/queryComplexityPlugin.d.ts(2,41): error TS2307: Cannot find module 'graphql-query-complexity'.`

Thank you for all the work!

**Comment by tgriesser** [comment]
Oops, should be fixed in `rc.11`
