### ISSUE TITLE
Questions/requests regarding implementing custom plugins

### ISSUE THREAD

**Issue by santialbo** [prisma-labs/nexus#379]
In order to support an offset-limit based pagination I decided to implement my own plugin.
Using the connectionPlugin as a base I came up with what's on [this gist](https://gist.github.com/santialbo/1fb6d65b373365d5539a9b2ad1a95bd0). I'm pretty happy with the result and it works great but I have a couple of concerns:
- Is this the way to go looking forward? Should I've maybe opted to create a higher order function instead of extending `t.`?
- I'm importing a bunch of helper types that are coming from 'nexus/dist/core' rather than 'nexus'.  Would it be possible for one of the next versions (maybe when moved to @nexus/schema) to expose all of those helper types?

Thanks a lot

**Comment by santialbo** [comment]
@tgriesser I'm sorry to ping you like this, I'd love to hear your opinion on this 🙏

**Comment by tgriesser** [comment]
> Would it be possible for one of the next versions (maybe when moved to @nexus/schema) to expose all of those helper types?

You can import `core` from `@nexus/schema` to get access to them

> Is this the way to go looking forward? Should I've maybe opted to create a higher order function instead of extending t.?

I think it's probably fine to extend `t.`

I believe you should also be able to use/extend the existing `connectionPlugin` config to create a limit/offset based pagination, but I think the gist looks fine too.

**Comment by santialbo** [comment]
Thanks a lot for the answer!
