### ISSUE TITLE
Typing a JSON argument to a query

### ISSUE THREAD

**Issue by dylanirlbeck** [prisma-labs/nexus#388]
Hi all. So I'm relatively new to `nexus` and am having trouble figuring out how to correctly type an argument of type `JSON!` to a query. The code looks roughly like this so far:

```es6
    t.field("someQuery", {
      type: AppType,
      nullable: false,
      args: {
        uuid: idArg({ required: true }),
        files: jsonArg({ required: true }), // Error here --- I'm not sure what to put since jsonArg doesn't exist
      },
      resolve: async (_, { uuid, files }, _) => {...}
```

for the following query:

```
someQuery (uuid: ID!, files: JSON!)
```

Any help would be much appreciated! I can try and give more information if needed. Again, I'm pretty new to `nexus` so this might just be a silly mistake on my part. Thanks!

**Comment by BjornLuG** [comment]
Assuming you're using [graphql-type-json](https://github.com/taion/graphql-type-json), you can turn it into a nexus scalar like this:

```ts
import GraphQLJSON from 'graphql-type-json'

export const Json = GraphQLJSON
```

And then use the argument: `files: arg({ type: 'JSON', required: true })`

More info about [custom nexus scalars](https://nexus.js.org/docs/api-scalartype#example-of-datetime-scalar)

**Comment by santialbo** [comment]
This is my `json.ts` file which is included in the schema.
```ts
import GraphQLJSON, { GraphQLJSONObject } from "graphql-type-json";
import { arg, asNexusMethod, core } from "nexus";

export const JSONObject = asNexusMethod(GraphQLJSONObject, "jsonObject");
export const JSON = asNexusMethod(GraphQLJSON, "json");

export function jsonObjectArg(opts: core.NexusArgConfig<"JSONObject">) {
  return arg({ ...opts, type: "JSONObject" });
}

export function jsonArg(opts: core.NexusArgConfig<"JSON">) {
  return arg({ ...opts, type: "JSON" });
}
```

It allows to use the `jsonArg` that you needed and also type fields on an object with

```ts
    t.jsonObject("options", {
      description: "The options of ...",
      nullable: true
    });
```

**Comment by dylanirlbeck** [comment]
Thanks for the help everyone! I'll close this issue for now and re-open it if I run into problems.
