### ISSUE TITLE
Connection Plugin Type Error: hasNextPage 

### ISSUE THREAD

**Issue by seanemmer** [prisma-labs/nexus#395]
I am following the documentation guide to implementing a simple connection using connectionFromArray: https://nexus.js.org/docs/plugin-connection

My implementation is as follows:

```
export const paginatedMembers = queryField(t => {
  t.connectionField('paginatedMembers', {
    type: 'Contact',
    async resolve(root, args, ctx, info) {
      return connectionFromArray(await ctx.prisma.contact.findMany(), args)
    }
  })
})
```

This results in the following type error:

```
Type 'PageInfo' is not assignable to type '{ endCursor?: MaybePromise<string | null | undefined>; hasNextPage: MaybePromise<boolean>; hasPreviousPage: MaybePromise<boolean>; startCursor?: MaybePromise<...>; }'.
                        Types of property 'hasNextPage' are incompatible.
                          Type 'boolean | null | undefined' is not assignable to type 'MaybePromise<boolean>'.
                            Type 'undefined' is not assignable to type 'MaybePromise<boolean>'.
```

It looks like Nexus is already casting hasNextPage to boolean (the graphql query returns hasNextPage: false)

However, the current type definition is not compatible with connectionFromArray's optional pageInfo.hasNextPage property.

**Comment by tgriesser** [comment]
I believe the `hasNextPage` DefinitelyTyped typing is [actually incorrect here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/97120d440e7a4e3096067ac3df8de7a9bb891921/types/graphql-relay/index.d.ts#L103-L104), it should not allow `undefined`.

You could open a PR to fix this in the DefinitelyTyped definitions, or handle it manually as it is done in the kitchen sink example: https://github.com/prisma-labs/nexus/blob/5b0b23138789d6f384c1c2e6f44bc116d54691d6/examples/kitchen-sink/src/kitchen-sink-definitions.ts#L250-L262
